server:
  port: 8013  
---
spring:
#Es muy importante que esta etiqueta "profiles" la dejes en "default" porque se empieza a rayar
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/db_catalog
    username: root
    password: root
    test-while-idle: true
    validation-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
#Hibernate creara estas tablas si es que no existen :o oh my god
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#Estrategia de nombres para los nombres y tablas
      dialect: org.hibernate.dialect.MySQL5Dialect
      show_sql: true
      use_sql_comments: true

