spring:
  profiles:
    active: development

---
server:
  port: 8021
spring:
  profiles: development
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/phrdb
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/phrdb
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
