# Zuul-proxied services can be found by calling /services/subject, /services/verb, etc.
zuul:
  prefix: /apps
server:
  port: 8030  
  
---
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.40:8010/eureka/