spring:
  profiles:
    active: heroku

---
spring:
  profiles: heroku
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}
  datasource:
    url: jdbc:postgresql://ec2-54-225-119-223.compute-1.amazonaws.com:5432/d26nkmv4pealv4
    username: nbxbfdxslqwpeo
    password: f023412c713cae5e35c932ca1187be491036a1b16cd08caad07a5a1b1776e6ec
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    #removeAbandonedTimeout: 600
    removeAbandoned: true    
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true

---
server:
  port: 8014  
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/pacientdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.33:8010/eureka/

---
spring:
  profiles: test
  application:
    name: ehu-pacient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pacientdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      