spring:
  profiles:
    active: heroku

---
spring:
  profiles: heroku
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    #removeAbandonedTimeout: 600
    removeAbandoned: true    
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true

security:
  user:
    password: ${eureka.password}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password:  ${USER_PASSWORD:password}
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

---
server:
  port: 8016  
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/emrdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.42:8010/eureka/

---
spring:
  profiles: test
  application:
    name: ehu-emr-service
  datasource:
    url: jdbc:postgresql://localhost:5432/emrdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      