spring:
  profiles:
    active: test


---
server:
  port: 8014  
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/emrdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.42:8010/eureka/

---
spring:
  profiles: test
  application:
    name: ehu-emr-service
  datasource:
    url: jdbc:postgresql://localhost:5432/emrdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      