server:
  port: 8014  
---
spring:
#Is very important that this tag "profiles" let it in "default" because else the project won't run
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/db_pacient
    username: root
    password: root
    test-while-idle: true
    validation-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
#Hibernate will create these tables if these don't exist (surprising)
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#Strategy of names for the names and tables
      dialect: org.hibernate.dialect.MySQL5Dialect
      show_sql: true
      use_sql_comments: true


---
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.35:8010/eureka/
      