server:
  port: 8013

---
spring:
#Is very important that this tag "profiles" let it in "default" because else the project won't run
  profiles: default
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true

---
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #el localhost debes cambiarlo por la ip del descubridor: http://192.168.1.33:8010/eureka/
      defaultZone: http://localhost:8010/eureka/

---
spring:
  application:
    name: ehu-catalog-service
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
